"""cria tabela alerta_estoque

Revision ID: 3d5c73635a1e
Revises: 16f29a063f8e
Create Date: 2026-08-20 11:19:09.173420

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d5c73635a1e"
down_revision: str | Sequence[str] | None = "16f29a063f8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerta_estoque",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quantidade_no_alerta", sa.Integer(), nullable=False),
        sa.Column("estoque_minimo_no_alerta", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolvido_em", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('aberto', 'resolvido')", name=op.f("alerta_estoque_status_valido_check")
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produto.id"],
            name=op.f("alerta_estoque_produto_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("alerta_estoque_pkey")),
    )
    op.create_index(
        "alerta_estoque_produto_aberto_idx",
        "alerta_estoque",
        ["produto_id"],
        unique=True,
        postgresql_where=sa.text("status = 'aberto'"),
    )
    op.create_index(
        op.f("alerta_estoque_produto_id_idx"), "alerta_estoque", ["produto_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("alerta_estoque_produto_id_idx"), table_name="alerta_estoque")
    op.drop_index(
        "alerta_estoque_produto_aberto_idx",
        table_name="alerta_estoque",
        postgresql_where=sa.text("status = 'aberto'"),
    )
    op.drop_table("alerta_estoque")
    # ### end Alembic commands ###
