"""cria tabelas produto e usuario

Revision ID: 16f29a063f8e
Revises:
Create Date: 2026-08-20 09:42:26.567010

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16f29a063f8e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "produto",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("descricao", sa.String(length=1000), nullable=True),
        sa.Column("preco", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantidade_estoque", sa.Integer(), nullable=False),
        sa.Column("estoque_minimo", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("preco >= 0", name=op.f("produto_preco_nao_negativo_check")),
        sa.CheckConstraint(
            "quantidade_estoque >= 0", name=op.f("produto_estoque_nao_negativo_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("produto_pkey")),
    )
    op.create_index(op.f("produto_nome_idx"), "produto", ["nome"], unique=False)
    op.create_index(op.f("produto_preco_idx"), "produto", ["preco"], unique=False)
    op.create_table(
        "usuario",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=128), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("usuario_pkey")),
    )
    op.create_index(op.f("usuario_email_idx"), "usuario", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("usuario_email_idx"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_index(op.f("produto_preco_idx"), table_name="produto")
    op.drop_index(op.f("produto_nome_idx"), table_name="produto")
    op.drop_table("produto")
    # ### end Alembic commands ###
