"""cria tabela movimento_estoque

Revision ID: 8e42a2a8a830
Revises: 3d5c73635a1e
Create Date: 2026-08-20 11:23:16.363668

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e42a2a8a830"
down_revision: str | Sequence[str] | None = "3d5c73635a1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movimento_estoque",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("referencia", sa.String(length=120), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("saldo_apos", sa.Integer(), nullable=False),
        sa.Column("motivo", sa.String(length=200), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produto.id"],
            name=op.f("movimento_estoque_produto_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("movimento_estoque_pkey")),
        sa.UniqueConstraint("referencia", name=op.f("movimento_estoque_referencia_key")),
    )
    op.create_index(
        op.f("movimento_estoque_produto_id_idx"), "movimento_estoque", ["produto_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("movimento_estoque_produto_id_idx"), table_name="movimento_estoque")
    op.drop_table("movimento_estoque")
    # ### end Alembic commands ###
